/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductPidRouteImport } from './routes/Product.$pid'

const ProductLazyRouteImport = createFileRoute('/Product')()

const ProductLazyRoute = ProductLazyRouteImport.update({
  id: '/Product',
  path: '/Product',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Product.lazy').then((d) => d.Route))
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPidRoute = ProductPidRouteImport.update({
  id: '/$pid',
  path: '/$pid',
  getParentRoute: () => ProductLazyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/Product': typeof ProductLazyRouteWithChildren
  '/Product/$pid': typeof ProductPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/Product': typeof ProductLazyRouteWithChildren
  '/Product/$pid': typeof ProductPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/Product': typeof ProductLazyRouteWithChildren
  '/Product/$pid': typeof ProductPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/Product' | '/Product/$pid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/Product' | '/Product/$pid'
  id: '__root__' | '/' | '/profile' | '/Product' | '/Product/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ProductLazyRoute: typeof ProductLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Product': {
      id: '/Product'
      path: '/Product'
      fullPath: '/Product'
      preLoaderRoute: typeof ProductLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Product/$pid': {
      id: '/Product/$pid'
      path: '/$pid'
      fullPath: '/Product/$pid'
      preLoaderRoute: typeof ProductPidRouteImport
      parentRoute: typeof ProductLazyRoute
    }
  }
}

interface ProductLazyRouteChildren {
  ProductPidRoute: typeof ProductPidRoute
}

const ProductLazyRouteChildren: ProductLazyRouteChildren = {
  ProductPidRoute: ProductPidRoute,
}

const ProductLazyRouteWithChildren = ProductLazyRoute._addFileChildren(
  ProductLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ProductLazyRoute: ProductLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
